// Auth action types
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_MARK_ATTENDANCE = 'AUTH_MARK_ATTENDANCE';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const ENDOFWORK_SUCCESS = 'ENDOFWORK_SUCCESS';
export const ENDOFWORK_FAIL = 'ENDOFWORK_FAIL';

// Attendance action types
export const FETCH_ATTENDANCE_START = 'FETCH_ATTENDANCE_START';
export const FETCH_ATTENDANCE_SUCCESS = 'FETCH_ATTENDANCE_SUCCESS';
export const FETCH_ATTENDANCE_FAIL = 'FETCH_ATTENDANCE_FAIL';